OwnedStream::new(
    OwnedDictionary::from_iter([
        (
            "Type".into(),
            OwnedName::from("XObject").into(),
        ),
        (
            "Subtype".into(),
            OwnedName::from("Form").into(),
        ),
        (
            "BBox".into(),
            OwnedArray::from_iter([
                0.into(),
                0.into(),
                100.into(),
                100.into(),
            ])
            .into(),
        ),
        (
            "FormType".into(),
            1.into(),
        ),
        (
            "Matrix".into(),
            OwnedArray::from_iter([
                1.into(),
                0.into(),
                0.into(),
                1.into(),
                0.into(),
                0.into(),
            ])
            .into(),
        ),
        (
            "Resources".into(),
            unsafe { Reference::new_unchecked(11, 0).into() },
        ),
        ("Length".into(), 15.into()),
        ("Filter".into(), OwnedName::from("FlateDecode").into()),
    ]),
    &buffer[155..170],
)
